server:
  port: 8855
spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: 'r2dbcs:mysql://122.9.33.79:3307/myblog'
    username: root
    password: 1157
    pool:
      enabled: true
      initial-size: 1
      validation-query: select 1
      max-life-time: 30000

  jackson:
    default-property-inclusion: non_null
  webflux:
    multipart:
      max-headers-size: 10MB

logging:
  level:
    root: info
    com:
      example: debug
    org:
      springframework:
        r2dbc: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbcs:mysql://${dhost}/myblog?serverTimezone=Asia/Shanghai
    username: ${dusername}
    password: ${dpassword}
    pool:
      max-size: 200
logging:
  level:
    root: info
    com:
      example: info
    org:
      springframework:
        r2dbc: warn